using Fracture.Engine.Physics.Dynamics;
using Microsoft.Xna.Framework;

namespace Fracture.Engine.Physics.Contacts
{
    /// <summary>
    /// Structure that contains contact information of two bodies. These
    /// are generated by the narrow phase contact solver.
    /// </summary>
    public struct Contact
    {
        #region Properties
        /// <summary>
        /// First body involved in the collision. Always guaranteed to be
        /// dynamic or sensor.
        /// </summary>
        public Body A
        {
            get;
            set;
        }

        /// <summary>
        /// Second body involved in the collision. Always guaranteed to be
        /// static of dynamic.
        /// </summary>
        public Body B
        {
            get;
            set;
        }

        /// <summary>
        /// Translation required to separate bodies from each other.
        /// </summary>
        public Vector2 Translation
        {
            get;
            set;
        } 
        #endregion
    }
}
